apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ocs-client-operator-console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ocs-client-operator-console
    spec:
      containers:
        - name: ocs-client-operator-console
          image: ocs-client-operator-console:latest
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /plugin-manifest.json
              port: 9001
              scheme: HTTPS
            initialDelaySeconds: 1000
            periodSeconds: 60
          ports:
            - containerPort: 9001
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: ocs-client-operator-console-serving-cert
              mountPath: /var/serving-cert
              readOnly: true
            - name: ocs-client-operator-console-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: ocs-client-operator-console-nginx-log
              mountPath: /var/log/nginx
            - name: ocs-client-operator-console-nginx-tmp
              mountPath: /var/lib/nginx/tmp
      volumes:
        - name: ocs-client-operator-console-serving-cert
          secret:
            secretName: ocs-client-operator-console-serving-cert
        - name: ocs-client-operator-console-nginx-conf
          configMap:
            name: ocs-client-operator-console-nginx-conf
        - name: ocs-client-operator-console-nginx-log
          emptyDir: {}
        - name: ocs-client-operator-console-nginx-tmp
          emptyDir: {}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: ocs-client-operator-controller-manager
      tolerations:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
      priorityClassName: system-cluster-critical
