apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ocs-client-metrics-cert-secret
  creationTimestamp: null
  labels:
    app: ocs-client-operator
    server: metrics
  name: ocs-client-operator-metrics
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 0
  selector:
    app: ocs-client-operator
status:
  loadBalancer: {}
