apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ocs-client-webhook-cert-secret
  creationTimestamp: null
  labels:
    app: ocs-client-operator
    server: webhook
  name: ocs-client-operator-webhook-server
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 7443
  selector:
    app: ocs-client-operator
  type: ClusterIP
status:
  loadBalancer: {}
