apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
  name: prometheus-provider-alert-rules
spec:
  groups:
  - name: provider-alert.rules
    rules:
    - alert: OcsProviderAlert
      annotations:
        description: 'Storage provider alert "{{ $labels.provider_alert_name }}" is firing. Severity: {{ $labels.severity }}.'
        message: 'Provider alert {{ $labels.provider_alert_name }} is active on the storage provider cluster.'
        severity_level: '{{ $labels.severity }}'
        storage_type: ceph
      expr: |
        ocs_client_provider_alert > 0
      labels:
        severity: warning
  - name: mirroring-alert.rules
    rules:
    - alert: OdfPoolMirroringImageHealth
      annotations:
        description: Mirroring image(s) (PV) in the pool {{ $labels.name }} and rados namespace {{ $labels.rados_namespace }} are in
          Unknown state for more than 1m. Mirroring might not work as expected in
          namespace:cluster {{ $labels.namespace }}:{{ $labels.managedBy }}.
        message: Mirroring image(s) (PV) in the pool {{ $labels.name }} and rados namespace {{ $labels.rados_namespace }} are in Unknown
          state in namespace:cluster {{ $labels.namespace }}:{{ $labels.managedBy
          }}.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/OdfPoolMirroringImageHealth.md
        severity_level: warning
        storage_type: ceph
      expr: |
        (ocs_pool_mirroring_image_health{job="ocs-metrics-exporter"}  * on (namespace, managedBy, rados_namespace) group_left() (max by(namespace, managedBy, rados_namespace) (ocs_pool_mirroring_status{job="ocs-metrics-exporter"}))) == 1
      for: 1m
      labels:
        mirroring_image_status: unknown
        severity: warning
    - alert: OdfPoolMirroringImageHealth
      annotations:
        description: Mirroring image(s) (PV) in the pool {{ $labels.name }} and rados namespace {{ $labels.rados_namespace }} are in
          Warning state for more than 1m. Mirroring might not work as expected in
          namespace:cluster {{ $labels.namespace }}:{{ $labels.managedBy }}.
        message: Mirroring image(s) (PV) in the pool {{ $labels.name }} and rados namespace {{ $labels.rados_namespace }} are in Warning
          state for cluster {{ $labels.namespace }}:{{ $labels.managedBy }}.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/OdfPoolMirroringImageHealth.md
        severity_level: warning
        storage_type: ceph
      expr: |
        (ocs_pool_mirroring_image_health{job="ocs-metrics-exporter"}  * on (namespace, managedBy, rados_namespace) group_left() (max by(namespace, managedBy, rados_namespace) (ocs_pool_mirroring_status{job="ocs-metrics-exporter"}))) == 2
      for: 1m
      labels:
        mirroring_image_status: warning
        severity: warning
    - alert: OdfPoolMirroringImageHealth
      annotations:
        description: Mirroring image(s) (PV) in the pool {{ $labels.name }} and rados namespace {{ $labels.rados_namespace }} are in
          Error state for more than 10s. Mirroring is not working as expected in namespace:cluster
          {{ $labels.namespace }}:{{ $labels.managedBy }}.
        message: Mirroring image(s) (PV) in the pool {{ $labels.name }} and rados namespace {{ $labels.rados_namespace }} are in Error
          state for cluster {{ $labels.namespace }}:{{ $labels.managedBy }}.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/OdfPoolMirroringImageHealth.md
        severity_level: error
        storage_type: ceph
      expr: |
        (ocs_pool_mirroring_image_health{job="ocs-metrics-exporter"}  * on (namespace, managedBy, rados_namespace) group_left() (max by(namespace, managedBy, rados_namespace) (ocs_pool_mirroring_status{job="ocs-metrics-exporter"}))) == 3
      for: 10s
      labels:
        mirroring_image_status: error
        severity: critical
    - alert: ODFPersistentVolumeMirrorStatus
      annotations:
        description: Persistent volume {{ $labels.name }}/{{ $labels.namespace }}
          is not mirrored properly to peer site {{ $labels.site_name }} for more than
          1m. RBD image={{ $labels.image }} and CephBlockPool={{ $labels.pool_name
          }}. Please check namespace:cluster {{ $labels.namespace }}:{{ $labels.managedBy
          }}.
        message: Persistent volume {{ $labels.name }}/{{ $labels.namespace }} is not
          mirrored properly to peer site {{ $labels.site_name }} in namespace:cluster
          {{ $labels.namespace }}:{{ $labels.managedBy }}.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/ODFPersistentVolumeMirrorStatus.md
        severity_level: error
        storage_type: ceph
      expr: |
        ocs_rbd_mirror_image_state{job="ocs-metrics-exporter"} * on(image,pool_name) group_left(name,namespace,managedBy) ocs_rbd_pv_metadata{job="ocs-metrics-exporter"} == 1
      for: 1m
      labels:
        severity: critical
    - alert: ODFPersistentVolumeMirrorStatus
      annotations:
        description: Status unknown for Persistent volume {{ $labels.name }}/{{ $labels.namespace
          }} to peer site {{ $labels.site_name }} for more than 1m. RBD image={{ $labels.image
          }} and CephBlockPool={{ $labels.pool_name }}. Please check namespace:cluster
          {{ $labels.namespace }}:{{ $labels.managedBy }}
        message: Status unknown for Persistent volume {{ $labels.name }}/{{ $labels.namespace
          }} mirroring to peer site {{ $labels.site_name }} in namespace:cluster {{
          $labels.namespace }}:{{ $labels.managedBy }}.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/ODFPersistentVolumeMirrorStatus.md
        severity_level: warning
        storage_type: ceph
      expr: |
        ocs_rbd_mirror_image_state{job="ocs-metrics-exporter"} * on(image,pool_name) group_left(name,namespace,managedBy) ocs_rbd_pv_metadata{job="ocs-metrics-exporter"} == 0
      for: 1m
      labels:
        severity: warning
  - name: ceph-blocklist-alerts.rules
    rules:
    - alert: ODFRBDClientBlocked
      annotations:
        description: An RBD client might be blocked by Ceph on node {{ $labels.node_name
          }} in namespace:cluster {{ $labels.namespace }}:{{ $labels.managedBy }}.
          This alert is triggered when the ocs_rbd_client_blocklisted metric reports
          a value of 1 for the node and there are pods in a CreateContainerError state
          on the node. This may cause the filesystem for the PVCs to be in a read-only
          state. Please check the pod description for more details.
        message: An RBD client might be blocked by Ceph on node {{ $labels.node_name
          }} in namespace:cluster {{ $labels.namespace }}:{{ $labels.managedBy }}.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/ODFRBDClientBlocked.md
        severity_level: error
      expr: |
        (
          ocs_rbd_client_blocklisted{node=~".+"} == 1
        )
        and on(node) (
          kube_pod_container_status_waiting_reason{reason="CreateContainerError"}
          * on(pod, namespace, managedBy) group_left(node)
          kube_pod_info
        ) > 0
      for: 10s
      labels:
        severity: warning
  - name: ceph-rbd-children.rules
    rules:
    - alert: HighRBDCloneSnapshotCount
      annotations:
        description: RBD clones/snapshots count has exceeded 200 for image {{ $labels.image }} under namespace {{ $labels.namespace }}.
          Please take appropriate action before we have any impact on the performance.
        message: RBD clones/snapshots count has exceeded the threshold limit.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/HighRBDCloneSnapshotCount.md
        severity_level: warning
      expr: |
        ocs_rbd_children_count > 200
      for: 30s
      labels:
        severity: warning
  - name: ceph-fs-stale-subvolume.rules
    rules:
    - alert: CephFSStaleSubvolume
      annotations:
        description: Number of CephFS subvolumes are greater than the number of PersistentVolumes in the cluster.
        message: There could be stale subvolumes that are not claimed or utilized. Please investigate for possible stale or orphaned subvolumes.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/CephFSStaleSubvolume.md
        severity_level: warning
      expr: |
        sum(ocs_cephfs_subvolume_count) >
        (
          count(
            kube_persistentvolume_info
            * on (storageclass) group_left()
            kube_storageclass_info{provisioner=~".*cephfs.csi.ceph.com"}
          ) or vector(0)
        )
      labels:
        severity: warning
