---
name: lint-and-spellcheck
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches: ['*']

permissions:
  contents: read
  pull-requests: read

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: codespell
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          exclude_file: go.sum
          check_filenames: true
          check_hidden: true
          skip: vendor
  commitlint:
    name: commitlint
    runs-on: ubuntu-latest
    if: github.triggering_actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
          # we check commitlint for every 20 commits
          fetch-depth: 20
      - name: run commitlint
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
        with:
          configFile: './.github/workflows/conf/commitlintrc.json'
          helpURL: |
            Some helpful links
            Contribution Guide -> https://github.com/red-hat-storage/odf-operator/blob/main/CONTRIBUTING.md#commit-structure
            Naming Conventions -> https://commitlint.js.org/#/concepts-commit-conventions
            Rules -> https://commitlint.js.org/#/reference-rules
            How to Write a Good Git Commit Message -> https://chris.beams.io/posts/git-commit
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_file: ./.github/workflows/conf/yamllint.yaml
          file_or_dir: .  # Recursive on all yaml files
